FROM python:3.13-alpine

WORKDIR /app

COPY requirements/common.txt requirements/common.txt
COPY requirements/dev.txt requirements/dev.txt

RUN pip install -r requirements/dev.txt

COPY cli cli
COPY scripts scripts
COPY src src
COPY pyproject.toml pyproject.toml

EXPOSE 8000

ENV SQUADY_APP_DEBUG=true

CMD sh -c "./scripts/cmd/dev"
