#!/bin/sh

# Run migrations
alembic upgrade head

# Run clickhouse migrations
python -m src.clickhouse.migrations.create

# Create superuser
python -m cli superuser create \
  --username $SQUADY_SUPERUSER_USERNAME \
  --email $SQUADY_SUPERUSER_EMAIL \
  --password $SQUADY_SUPERUSER_PASSWORD

# Populate users
python -m cli populate users

# Populate roles
python -m cli populate roles

# Populate skills
python -m cli populate skills

# Populate resumes
python -m cli populate resumes

# Start development server
uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
