#!/bin/sh

# Run migrations
alembic upgrade head

# Run clickhouse migrations
python -m src.clickhouse.migrations.create

# Create superuser
python -m cli superuser create \
  --username $SQUADY_SUPERUSER_USERNAME \
  --email $SQUADY_SUPERUSER_EMAIL \
  --password $SQUADY_SUPERUSER_PASSWORD

# Populate roles
python -m cli populate roles

# Populate skills
python -m cli populate skills
  
# Start production server
uvicorn src.app:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips="*" --proxy-headers