"""Add email to user

Revision ID: 1299ab199276
Revises: 535098875eea
Create Date: 2025-07-16 21:33:20.337222

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1299ab199276"
down_revision: str | Sequence[str] | None = "535098875eea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(), nullable=False))
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "is_verified")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
