"""refresh teams

Revision ID: 2d85279ecf7f
Revises: 5787a59d25ce
Create Date: 2025-10-29 16:52:08.453647

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2d85279ecf7f"
down_revision: str | Sequence[str] | None = "5787a59d25ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_to_user", sa.Column("resume_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "team_to_user", "resume", ["resume_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team_to_user", type_="foreignkey")  # type: ignore
    op.drop_column("team_to_user", "resume_id")
    # ### end Alembic commands ###
