"""add teams

Revision ID: 5787a59d25ce
Revises: 8e8ee896a01f
Create Date: 2025-10-28 17:06:27.561529

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5787a59d25ce"
down_revision: str | Sequence[str] | None = "8e8ee896a01f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("about", sa.String(), nullable=True),
        sa.Column("tasks", sa.String(), nullable=True),
        sa.Column("leader_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Enum("active", "in_check", "finished", name="statusenum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["leader_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_to_user",
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_to_user")
    op.drop_table("team")
    # ### end Alembic commands ###
