"""add indexes

Revision ID: 8e8ee896a01f
Revises: e994da92ad92
Create Date: 2025-08-07 22:08:42.311350

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8e8ee896a01f"
down_revision: str | Sequence[str] | None = "e994da92ad92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_role_name_trgm",
        "role",
        [sa.literal_column("lower(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    op.create_index(
        "uq_role_name_lower",
        "role",
        [sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_index(
        "ix_skill_name_trgm",
        "skill",
        [sa.literal_column("lower(name)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"lower(name)": "gin_trgm_ops"},
    )
    op.create_index(
        "uq_skill_name_lower",
        "skill",
        [sa.literal_column("lower(name)")],
        unique=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_skill_name_lower", table_name="skill")
    op.drop_index(
        "ix_skill_name_trgm", table_name="skill", postgresql_using="gin", postgresql_ops={"lower(name)": "gin_trgm_ops"}
    )
    op.drop_index("uq_role_name_lower", table_name="role")
    op.drop_index(
        "ix_role_name_trgm", table_name="role", postgresql_using="gin", postgresql_ops={"lower(name)": "gin_trgm_ops"}
    )

    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
