"""fix date type

Revision ID: 91f2bfab44e8
Revises: ddaff0b889aa
Create Date: 2025-11-01 20:18:59.330463

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "91f2bfab44e8"
down_revision: str | Sequence[str] | None = "ddaff0b889aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event",
        "start_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
    )
    op.alter_column(
        "event", "end_date", existing_type=postgresql.TIMESTAMP(timezone=True), type_=sa.Date(), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event", "end_date", existing_type=sa.Date(), type_=postgresql.TIMESTAMP(timezone=True), existing_nullable=False
    )
    op.alter_column(
        "event",
        "start_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
