"""fix date type

Revision ID: ddaff0b889aa
Revises: c444257aaacd
Create Date: 2025-11-01 19:13:52.069866

"""

from typing import Sequence

revision: str = "ddaff0b889aa"
down_revision: str | Sequence[str] | None = "c444257aaacd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
