"""add personal data

Revision ID: dfcade2b1441
Revises: fa5ca7a22999
Create Date: 2025-07-27 18:45:33.617540

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dfcade2b1441"
down_revision: str | Sequence[str] | None = "fa5ca7a22999"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("full_name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("birth_date", sa.Date(), nullable=True))
    op.add_column("user", sa.Column("city", sa.String(), nullable=True))
    op.add_column("user", sa.Column("telegram", sa.String(), nullable=True))
    op.add_column("user", sa.Column("about", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "about")
    op.drop_column("user", "telegram")
    op.drop_column("user", "city")
    op.drop_column("user", "birth_date")
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###
