"""add role

Revision ID: fa5ca7a22999
Revises: 1299ab199276
Create Date: 2025-07-22 21:57:47.287168

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fa5ca7a22999"
down_revision: str | Sequence[str] | None = "1299ab199276"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    userrole = postgresql.ENUM("admin", "agent", "mentor", "participant", name="userrole")
    userrole.create(op.get_bind(), checkfirst=True)

    op.add_column("user", sa.Column("role", userrole, nullable=True))
    op.add_column("user", sa.Column("is_verified_agent", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "is_verified_agent")
    op.drop_column("user", "role")
    # ### end Alembic commands ###
